image: node:carbon-alpine

before_script:
  - yarn install --frozen-lockfile

cache: &cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - push

build:
  stage: build
  script:
    - yarn run build
  cache:
    <<: *cache
    policy: pull

push-to-aws:
  stage: push
  script:
    - echo "push to aws"