image: node:carbon-alpine

before_script:
  - yarn install --frozen-lockfile

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:prod: &build
  stage: build
  only:
    - master
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

build:dev:
  <<: *build
  only:
    - develop
  script:
    - yarn webpack
  variables:
    SELECT_URL: https://select.ridi.io
    SELECT_API: https://select-api.dev.ridi.io
    STORE_URL: https://master.test.ridi.io
    STORE_API: https://master.test.ridi.io
    PAY_URL: https://pay.ridi.io
    ACCOUNT_API: https://account.dev.ridi.io
    OAUTH2_CLIENT_ID: $DEV_OAUTH2_CLIENT_ID
    ASSET_PATH: ''
    SENTRY_DSN: ''

.deploy: &deploy
  image: ridibooks/gitlab-ci-docker-aws
  stage: deploy
  cache: {}
  before_script: []
  only:
    - master

develop:
  <<: *deploy
  only:
    - develop
  variables:
    AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}
  script:
    - aws s3 sync dist s3://${DEV_S3_BUCKET}
  after_script:
    - export INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths '/*' | jq .Invalidation.Id`
    - aws cloudfront wait invalidation-completed --distribution-id ${DEV_DISTRIBUTION_ID} --id ${INVALIDATION_ID}
  environment:
    name: develop
    url: https://select.ridi.io

staging:
  <<: *deploy
  variables:
    AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
  script:
    - aws s3 sync dist s3://${PROD_S3_BUCKET} --exclude "index.html" --exclude "*.map"
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli releases new ${CI_COMMIT_SHA}
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli releases set-commits ${CI_COMMIT_SHA} --auto
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli releases files ${CI_COMMIT_SHA} upload ./dist '~/*.js'
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli releases files ${CI_COMMIT_SHA} upload-sourcemaps ./dist/*.map
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli releases finalize ${CI_COMMIT_SHA}
  environment:
    name: staging
    url: https://select.ridibooks.com

production:
  <<: *deploy
  variables:
    AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
  when: manual
  script:
    - aws s3 sync dist/index.html s3://${PROD_S3_BUCKET}
  environment:
    name: production
    url: https://select.ridibooks.com
