version: "3.7"

services:
  web:
    image: node:12-alpine
    container_name: select
    working_dir: /app
    ports:
      - 9000
    init: true
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:select.local.ridi.io"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "yarn install --frozen-lockfile &&
             yarn start"

volumes:
  node_modules:

networks:
  default:
    external:
      name: ${EXTERNAL_NETWORK:-ridi}
