version: "3.6"

services:
  web:
    image: ridiselect/web
    build: .
    ports:
      - 9000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:select.local.ridi.io"
    volumes:
      - .:/app
      - modules:/app/node_modules
    networks:
      - traefik

volumes:
  modules:

networks:
  traefik:
    external:
      name: ${EXTERNAL_NETWORK:-ridi}
